# Generated by Django 5.0 on 2023-12-28 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
