# Generated by Django 5.0 on 2023-12-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='guest_name',
        ),
    ]
