# Generated by Django 4.2.8 on 2023-12-27 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programs',
        ),
    ]
