# Generated by Django 5.0 on 2023-12-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_room_hotel_delete_hotel_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=0)),
                ('nights', models.IntegerField(default=0)),
                ('massage', models.IntegerField(default=0)),
                ('safari', models.IntegerField(default=0)),
                ('camping', models.IntegerField(default=0)),
                ('seatrip', models.IntegerField(default=0)),
                ('diving', models.IntegerField(default=0)),
                ('snorkeling', models.IntegerField(default=0)),
            ],
        ),
    ]
