# Generated by Django 5.0 on 2023-12-29 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_registration'),
        ('bookings', '0006_alter_hotel_name_alter_room_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.hotel'),
        ),
    ]
