# Generated by Django 5.0 on 2023-12-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hobbies',
            field=models.CharField(choices=[('massage', 'Massage'), ('safari', 'Safari'), ('camping', 'Camping'), ('seatrip', 'Sea Trip'), ('diving', 'Diving'), ('snorkeling', 'Snorkeling')], max_length=255),
        ),
    ]
