# Generated by Django 5.0 on 2023-12-30 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_hotel'),
        ('bookings', '0008_alter_room_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.hotel'),
        ),
    ]
