# Generated by Django 5.0 on 2023-12-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailconfirmation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
    ]
