# Generated by Django 5.0 on 2023-12-30 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hotel',
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_registration', to='accounts.registration'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
