# Generated by Django 5.0 on 2023-12-30 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_hotel_customuser_registration_and_more'),
        ('bookings', '0008_alter_room_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='registration',
        ),
        migrations.AddField(
            model_name='customuser',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.hotel'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
