# Generated by Django 4.2.8 on 2023-12-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='check_in',
            field=models.DateTimeField(help_text='YYYY-MM-DDThh:mm[:ss[.uuuuuu]][+HH:MM|-HH:MM|Z]', unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.TextField(default='some_default_value'),
        ),
    ]
