# Generated by Django 5.0 on 2023-12-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='room_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
