# Generated by Django 5.0 on 2023-12-14 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='room_id',
            new_name='roomid',
        ),
    ]
