# Generated by Django 4.2.8 on 2023-12-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='uerId',
            new_name='user',
        ),
    ]
