# Generated by Django 5.0 on 2023-12-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_hotelbooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.ImageField(null=True, upload_to='room_images/'),
        ),
    ]
