# Generated by Django 4.2.8 on 2023-12-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_hotelbooking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='id',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.TextField(max_length=255, primary_key=True, serialize=True),
        ),
    ]
