# Generated by Django 4.2.5 on 2023-12-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_hotel_id_alter_hotel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
    operations = [
     migrations.AlterField(
    model_name='room',
    name='room_name',
    field=models.TextField(),  # Change this to TextField
),

     ]
