# Generated by Django 5.0 on 2023-12-21 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_room_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_image',
        ),
    ]
