# Generated by Django 5.0 on 2024-01-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_room_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=70, null=True),
        ),
    ]
